<?xml version="1.0"?>
<robot name="basic_shapes" xmlns:xacro="http://wiki.ros.org/xacro">

    <!-- differential drive macro -->
    <xacro:macro name="diff_wheel" params=" wheeldiam wheel_separation parent">
        <xacro:cylinder_shape name="left_wheel" r="${wheeldiam/2}" h="0.1" ori="0 0 0" rpy="0 0 0" rgb="Grey" m="0.1" friction="0.5"/>
        <joint name="left_wheel_joint" type="continuous">
            <axis xyz="0 0 1" rpy="0 0 0" />
            <parent link="${parent}"/>
            <child link="left_wheel"/>
            <origin xyz="0 ${-wheel_separation/2} 0" rpy="${pi/2} 0 0"/>
        </joint>

        <xacro:cylinder_shape name="right_wheel" r="${wheeldiam/2}" h="0.1" ori="0 0 0" rpy="0 0 0" rgb="Grey" m="0.1" friction="0.5"/>
        <joint name="right_wheel_joint" type="continuous">
            <axis xyz="0 0 1" rpy="0 0 0" />
            <parent link="${parent}"/>
            <child link="right_wheel"/>
            <origin xyz="0 ${wheel_separation/2} 0" rpy="${pi/2} 0 0"/>
        </joint>
    </xacro:macro>


</robot>