<?xml version="1.0"?>
<robot name="diff_wheel" xmlns:xacro="http://wiki.ros.org/xacro">

    <!-- differential drive macro -->
    <xacro:macro name="diff_wheel" params=" wheeldiam wheel_separation parent friction">
        <xacro:cylinder_shape name="left_wheel" r="${wheeldiam/2}" h="0.1" ori="0 0 0" rpy="0 0 0" rgb="Grey" m="0.1" friction="${friction}"/>
        <joint name="left_wheel_joint" type="continuous">
            <axis xyz="0 0 1" rpy="0 0 0" />
            <parent link="${parent}"/>
            <child link="left_wheel"/>
            <origin xyz="0 ${wheel_separation/2} 0" rpy="${-pi/2} 0 0"/>
        </joint>

        <xacro:cylinder_shape name="right_wheel" r="${wheeldiam/2}" h="0.1" ori="0 0 0" rpy="0 0 0" rgb="Grey" m="0.1" friction="${friction}"/>
        <joint name="right_wheel_joint" type="continuous">
            <axis xyz="0 0 1" rpy="0 0 0" />
            <parent link="${parent}"/>
            <child link="right_wheel"/>
            <origin xyz="0 ${-wheel_separation/2} 0" rpy="${-pi/2} 0 0"/>
        </joint>

        <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">

            <!-- Plugin update rate in Hz -->
            <updateRate>${update_rate}</updateRate>

            <!-- Name of left joint, defaults to `left_joint` -->
            <leftJoint>left_wheel_joint</leftJoint>

            <!-- Name of right joint, defaults to `right_joint` -->
            <rightJoint>right_wheel_joint</rightJoint>

            <!-- The distance from the center of one wheel to the other, in meters, defaults to 0.34 m -->
            <wheelSeparation>${wheel_separation}</wheelSeparation>

            <!-- Diameter of the wheels, in meters, defaults to 0.15 m -->
            <wheelDiameter>${wheeldiam}</wheelDiameter>

            <!-- Wheel acceleration, in rad/s^2, defaults to 0.0 rad/s^2 -->
            <wheelAcceleration>1.0</wheelAcceleration>

            <!-- Maximum torque which the wheels can produce, in Nm, defaults to 5 Nm -->
            <wheelTorque>20</wheelTorque>

            <!-- Topic to receive geometry_msgs/Twist message commands, defaults to `cmd_vel` -->
            <commandTopic>cmd_vel</commandTopic>

            <!-- Topic to publish nav_msgs/Odometry messages, defaults to `odom` -->
            <odometryTopic>odom</odometryTopic>

            <!-- Odometry frame, defaults to `odom` -->
            <odometryFrame>odom</odometryFrame>

            <!-- Robot frame to calculate odometry from, defaults to `base_footprint` -->
            <robotBaseFrame>base_footprint</robotBaseFrame>

            <!-- Odometry source, 0 for ENCODER, 1 for WORLD, defaults to WORLD -->
            <odometrySource>1</odometrySource>

            <!-- Set to true to publish transforms for the wheel links, defaults to false -->
            <publishWheelTF>true</publishWheelTF>

            <!-- Set to true to publish transforms for the odometry, defaults to true -->
            <publishOdom>true</publishOdom>

            <!-- Set to true to publish sensor_msgs/JointState on /joint_states for the wheel joints, defaults to false -->
            <publishWheelJointState>true</publishWheelJointState>

            <!-- Set to true to swap right and left wheels, defaults to true -->
            <legacyMode>false</legacyMode>
        </plugin>
        </gazebo>

    </xacro:macro>


</robot>