<?xml version="1.0"?>
<robot name="diff_wheel" xmlns:xacro="http://wiki.ros.org/xacro">

    <!-- differential drive macro -->
    <xacro:macro name="diff_wheel" params=" wheeldiam h wheel_separation parent friction rgb odom_topic:=odom pub_tf:=true">
        <xacro:wheel name="left_wheel" r="${wheeldiam/2}" h="${h}" ori="0 0 0" rpy="0 0 0" rgb="${rgb}" m="0.1" friction="${friction}"/>
        <joint name="left_wheel_joint" type="continuous">
            <axis xyz="0 0 1" rpy="0 0 0" />
            <parent link="${parent}"/>
            <child link="left_wheel"/>
            <origin xyz="0 ${wheel_separation/2} 0" rpy="${-pi/2} 0 0"/>
        </joint>

        <xacro:wheel name="right_wheel" r="${wheeldiam/2}" h="${h}" ori="0 0 0" rpy="0 0 0" rgb="${rgb}" m="0.1" friction="${friction}"/>
        <joint name="right_wheel_joint" type="continuous">
            <axis xyz="0 0 1" rpy="0 0 0" />
            <parent link="${parent}"/>
            <child link="right_wheel"/>
            <origin xyz="0 ${-wheel_separation/2} 0" rpy="${-pi/2} 0 0"/>
        </joint>

        <gazebo>
        <plugin name="diff_drive_controller" filename="libgazebo_ros_diff_drive.so">

            <!-- Plugin update rate in Hz -->
            <!-- <updateRate>${update_rate}</updateRate> -->
            <left_joint>left_wheel_joint</left_joint>
            <right_joint>right_wheel_joint</right_joint>

            <!-- kinematics -->
            <wheel_separation>${wheel_separation}</wheel_separation>
            <wheel_diameter>${wheeldiam}</wheel_diameter>

            <!-- limits -->
            <max_wheel_acceleration>1.0</max_wheel_acceleration>
            <max_wheel_torque>20</max_wheel_torque>

            <!-- topics and frames -->
            <command_topic>cmd_vel</command_topic>
            <odometry_topic>${odom_topic}</odometry_topic>
            <odometry_frame>odom</odometry_frame>
            <robot_base_frame>base_footprint</robot_base_frame>
            <!-- Odometry source, 0 for ENCODER, 1 for WORLD, defaults to WORLD -->
            <!-- <odometry_source>world</odometry_source> -->

            <!-- output -->
            <robot_base_frame>base_footprint</robot_base_frame>
            <publish_odom>true</publish_odom>
            <publish_odom_tf>${pub_tf}</publish_odom_tf>
            <publish_wheel_tf>true</publish_wheel_tf>
            <!-- <publish_wheel_joint_state>true</publish_wheel_joint_state> -->
            <!-- <publish_tf>true</publish_tf> -->
        </plugin>

        
        <plugin name="turtlebot3_joint_state" filename="libgazebo_ros_joint_state_publisher.so">
            <ros>
                <!-- <namespace>/tb3</namespace> -->
                <remapping>~/out:=joint_states</remapping>
            </ros>
            <update_rate>30</update_rate>
            <joint_name>left_wheel_joint</joint_name>
            <joint_name>right_wheel_joint</joint_name>
        </plugin>

        </gazebo>
        

    </xacro:macro>


</robot>