<?xml version="1.0"?>
<robot name="diff_wheel"
    xmlns:xacro="http://wiki.ros.org/xacro">

    <!-- differential drive macro -->
    <xacro:macro name="diff_wheel" params=" wheeldiam h wheel_separation parent friction rgb odom_topic:=odom pub_tf:=true">
        <xacro:cylinder_shape name="left_wheel" r="${wheeldiam/2}" h="${h}" ori="0 0 0" rpy="0 0 0" rgb="${rgb}" m="0.1" friction="${friction}"/>
        <joint name="left_wheel_joint" type="continuous">
            <axis xyz="0 0 -1" rpy="0 0 0" />
            <parent link="${parent}"/>
            <child link="left_wheel"/>
            <origin xyz="0 ${wheel_separation/2} 0" rpy="${-pi/2} 0 ${pi}"/>
        </joint>
        <transmission name="left_wheel_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="left_wheel_joint">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            <actuator name="left_wheel_actuator">
                <mechanicalReduction>1.0</mechanicalReduction>
                <hardwareInterface>VelocityJointInterface</hardwareInterface>
            </actuator>
        </transmission>

        <xacro:cylinder_shape name="right_wheel" r="${wheeldiam/2}" h="${h}" ori="0 0 0" rpy="0 0 0" rgb="${rgb}" m="0.1" friction="${friction}"/>
        <joint name="right_wheel_joint" type="continuous">
            <axis xyz="0 0 1" rpy="0 0 0" />
            <parent link="${parent}"/>
            <child link="right_wheel"/>
            <origin xyz="0 ${-wheel_separation/2} 0" rpy="${-pi/2} 0 0"/>
        </joint>
        <transmission name="right_wheel_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="right_wheel_joint">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            <actuator name="right_wheel_actuator">
                <mechanicalReduction>1.0</mechanicalReduction>
                <hardwareInterface>VelocityJointInterface</hardwareInterface>
            </actuator>
        </transmission>

        <!-- <gazebo>
            <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
                <robotNamespace>/</robotNamespace>
            </plugin>
        </gazebo> -->

    </xacro:macro>


</robot>