joint_limits:
    right_wheel_joint:
      has_position_limits: false
      min_position: 0
      max_position: 0
      has_velocity_limits: true
      max_velocity: 2.0
      min_velocity: -2.0
      has_acceleration_limits: true
      max_acceleration: 1.0
      has_jerk_limits: true
      max_jerk: 1.5
      has_effort_limits: false
      max_effort: 0
      min_effort: 0
    
    left_wheel_joint:
      has_position_limits: false
      min_position: 0
      max_position: 0
      has_velocity_limits: true
      max_velocity: 2.0
      min_velocity: -2.0
      has_acceleration_limits: true
      max_acceleration: 1.0
      has_jerk_limits: true
      max_jerk: 1.5
      has_effort_limits: false
      max_effort: 0
      min_effort: 0